flags: {}
extra-package-dbs: []
packages:
- .
allow-newer: true
extra-deps:
- attoparsec-0.13.2.0
- hashable-1.2.6.1
- integer-logarithms-1.0.2
- primitive-0.6.2.0
- scientific-0.3.5.2
- text-1.2.2.2
- vector-0.12.0.1
compiler: ghc-8.2
resolver: ghc-8.2
