name:                curious
version:             0.1.0.0
github:              "githubuser/curious"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2017 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/curious#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- recursion-schemes
- QuickCheck

library:
  source-dirs: src

executables:
  curious-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - curious

tests:
  curious-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - curious
